version: "3.8"

services:
    django:
        build: .
        container_name: cinema_app
        command: gunicorn cinema.wsgi:application --bind 0.0.0.0:8000
        volumes:
          - .:/usr/src/app
        ports:
          - "8000:8000"
        depends_on:
          - db
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mmuntean1!
        ports:
          - "5432:5432"

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "mmuntean1!"
#            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"