# Generated by Django 4.0.4 on 2022-06-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesimport',
            name='name',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
