# Generated by Django 4.0.4 on 2022-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_import', '0002_moviesimport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesimport',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
