# Generated by Django 4.0.4 on 2022-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_import', '0003_alter_moviesimport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesimport',
            name='file',
            field=models.FileField(upload_to='zipped_files'),
        ),
    ]
