# Generated by Django 4.0.4 on 2022-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='seats',
        ),
        migrations.AddField(
            model_name='hall',
            name='seats',
            field=models.ManyToManyField(to='cinemas.seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_nr',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
