# Generated by Django 4.0.4 on 2022-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_remove_hall_seats_hall_seats_alter_seat_seat_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietheater',
            name='halls',
        ),
        migrations.AddField(
            model_name='movietheater',
            name='halls',
            field=models.ManyToManyField(to='cinemas.hall'),
        ),
    ]
