# Generated by Django 4.0.4 on 2022-06-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_remove_movietheater_halls_movietheater_halls'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_row',
            field=models.CharField(default='', max_length=10),
        ),
    ]
