# Generated by Django 4.0.4 on 2022-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_seat_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seats',
            field=models.ManyToManyField(related_name='seats', to='cinemas.seat'),
        ),
    ]
