# Generated by Django 4.0.4 on 2022-06-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0006_alter_hall_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietheater',
            old_name='Street',
            new_name='street',
        ),
    ]
