# Generated by Django 4.0.4 on 2022-06-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_rename_street_movietheater_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='movietheater',
            name='halls',
        ),
        migrations.AddField(
            model_name='hall',
            name='movie_theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.movietheater'),
        ),
        migrations.AddField(
            model_name='seat',
            name='halls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.hall'),
        ),
    ]
