# Generated by Django 4.0.4 on 2022-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_remove_hall_seats_remove_movietheater_halls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_nr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_nr', 'halls')},
        ),
    ]
