# Generated by Django 4.0.4 on 2022-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0010_alter_seat_unique_together_hall_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
