# Generated by Django 4.0.4 on 2022-06-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_remove_hall_seats_remove_movietheater_halls_and_more'),
        ('reservation', '0002_remove_reservation_hall_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.seat'),
        ),
    ]
