# Generated by Django 4.0.4 on 2022-06-06 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_remove_hall_seats_remove_movietheater_halls_and_more'),
        ('movies', '0007_alter_movie_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0003_alter_reservation_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='movie_theater',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.seat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.hall')),
                ('assigned_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='playing_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.playingtime'),
        ),
    ]
