# Generated by Django 4.0.4 on 2022-06-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_remove_hall_seats_remove_movietheater_halls_and_more'),
        ('reservation', '0004_remove_reservation_date_remove_reservation_hour_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playingtime',
            unique_together={('assigned_hall', 'start_time')},
        ),
    ]
