# Generated by Django 4.0.4 on 2022-06-08 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemas', '0009_alter_seat_seat_nr_alter_seat_unique_together'),
        ('reservation', '0006_alter_reservation_playing_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('seat', 'user')},
        ),
    ]
