# Generated by Django 4.0.4 on 2022-06-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
