# Generated by Django 4.0.4 on 2022-06-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0009_alter_seat_seat_nr_alter_seat_unique_together'),
        ('reservation', '0009_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.seat'),
        ),
    ]
