# Generated by Django 4.0.4 on 2022-06-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0009_alter_seat_seat_nr_alter_seat_unique_together'),
        ('reservation', '0010_alter_reservation_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('playing_time', 'seat')},
        ),
    ]
