# Generated by Django 4.0.4 on 2022-06-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
