# Generated by Django 4.0.4 on 2022-06-17 06:36
from django.db import migrations, models
from django_q.tasks import schedule, Schedule


def create_periodic_tasks(apps, schema_editor):
    schedule(
        func="reservation.tasks.expired_reservations",
        name="Mark unconfirmed reservations as expired",
        minutes=1,
        repeats=-1,
        cluster="cinema",
        schedule_type=Schedule.MINUTES,
    )
    print(schedule)

class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_reservation_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_periodic_tasks),
    ]
