# Generated by Django 4.0.4 on 2022-05-31 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('poster', models.ImageField(upload_to='images/', verbose_name='Poster')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='Description')),
                ('imdb_id', models.CharField(max_length=30, null=True, unique=True, verbose_name='IMDB_id')),
                ('length_min', models.IntegerField(verbose_name='Lenght')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
