# Generated by Django 4.0.4 on 2022-06-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_trailer_url_alter_movie_length_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='', verbose_name='Poster'),
        ),
    ]
