# Generated by Django 4.0.4 on 2022-06-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_scheduled_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='time_scheduled_at',
            field=models.TimeField(null=True),
        ),
    ]
