# Generated by Django 4.0.4 on 2022-06-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_remove_hall_seats_remove_movietheater_halls_and_more'),
        ('movies', '0004_movie_date_scheduled_at_movie_time_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hall_is_playing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.hall'),
        ),
    ]
