# Generated by Django 4.0.4 on 2022-06-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_remove_hall_seats_remove_movietheater_halls_and_more'),
        ('movies', '0005_movie_hall_is_playing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('hall_is_playing', 'time_scheduled_at')},
        ),
    ]
