# Generated by Django 4.0.4 on 2022-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='csv')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
