# Generated by Django 4.0.4 on 2022-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
