# Generated by Django 4.0.4 on 2022-06-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_csv_is_used'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
