# Generated by Django 4.0.4 on 2022-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_delete_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=30, null=True, verbose_name='IMDB_id'),
        ),
    ]
