# Generated by Django 4.0.4 on 2022-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(max_length=500, upload_to='', verbose_name='Poster'),
        ),
    ]
